import assert from 'node:assert/strict';
import test from 'node:test';
import {HOUR,hourlyText,publishHourlyThread,selectPrompt} from './hourly-threads.mjs';
const NOW=Date.parse('2026-09-03T18:00:00Z');
function fixture(state={}) {const saved=[],posts=[];const api={get:async endpoint=>{if(endpoint==='/me')return {id:'account',username:'rapwire247'};if(endpoint==='/container')return {status:'FINISHED'};if(endpoint==='/published')return {id:'published',permalink:'https://www.threads.net/@rapwire247/post/x',text:state.pending.text};throw new Error(`Unexpected GET ${endpoint}`);},post:async(endpoint,params)=>{posts.push({endpoint,params});if(endpoint==='/account/threads')return {id:'container'};if(endpoint==='/account/threads_publish')return {id:'published'};throw new Error(`Unexpected POST ${endpoint}`);}};return {state,saved,posts,api,save:async()=>saved.push(structuredClone(state))};}
test('hourly text ends with the account handle',()=>assert.match(hourlyText('A clean question?'),/@rapwire247$/));
test('prompt rotation avoids a prompt used inside the repeat window',()=>{const first=selectPrompt({},NOW);const next=selectPrompt({next_prompt_index:0,posts:[{prompt:first.prompt,published_at:new Date(NOW-HOUR).toISOString()}]},NOW);assert.notEqual(first.prompt,next.prompt);});
test('hourly publisher persists container before requesting publish',async()=>{const f=fixture({});assert.equal(await publishHourlyThread({...f,userId:'account',now:NOW}),'processing');assert.equal(f.posts[0].endpoint,'/account/threads');assert.equal(f.saved.at(-1).pending.threads_container_id,'container');assert.equal(f.posts.filter(post=>post.endpoint.endsWith('publish')).length,0);});
test('hourly publisher verifies one post then enforces its one-hour limit',async()=>{const f=fixture({pending:{prompt:'Question?',text:hourlyText('Question?'),prompt_index:0,threads_container_id:'container',threads_container_checked_at:new Date(NOW-121_000).toISOString()}});assert.equal(await publishHourlyThread({...f,userId:'account',now:NOW}),'verified');assert.equal(f.posts.filter(post=>post.endpoint.endsWith('publish')).length,1);assert.equal(f.state.posts.length,1);assert.equal(await publishHourlyThread({...f,userId:'account',now:NOW+HOUR-1}),'hourly_limit');});
